### ISSUE TITLE
[COMPAT] C9 + 8bitdo adapter 2 = no controller

### ISSUE THREAD

**Issue by bmisiak** [mariotaku/moonlight-tv#145]
## Basic information

 - Device model: (   C9AUA    ) 
 - Firmware version: (    05.10.25   ) 
 - webOS version: (    4.9.3   ) 
 - Moonlight version: (   1.3.0    ) 
 - Is audio working: (    Yes   ) 
 - Is video working: (    1080p60   ) 
 - Is input working: (   No    ) 

## Description

I bought an 8bitdo "USB Adapter 2", the new black one. The TV does recognize a HID device but I haven't been able to get it to actually recognize any input.

**Comment by mariotaku** [comment]
There are several input mode for the adapter like Xinput mode and PS4 mode. Could you try switch between those and see if it works?

**Comment by TheVexedGerman** [comment]
Seems I have the same issue though it was able to be resolved with your suggestion. I have the 8bitdo wireless adapter 2 as well. It appears that the Mac input mode works. Dunno why the xinput recommended in the wiki doesn't work though, since a wired Xbox 360 controller does work and the TV recognizes an "XPad" with the 8bitdo.

I've tried the following modes that didn't work:

- Xinput
- Dinput
- PSC (partial)
- MD mode

Working:
- Mac mode

**Comment by sander1095** [comment]
@TheVexedGerman @mariotaku can you tell me how you switch input mode with the 8bitdo adapter v2? I have the v1 and wonder if this is possible for me.

**Comment by mariotaku** [comment]
@sander1095 It's View button (Select) + DPAD something. Please refer to the manual paper shipped with the adapter.

**Comment by wiistriker** [comment]
Same issue for me. Working in PSC mode but dont any vibration

**Comment by wiistriker** [comment]
@mariotaku during investigation of this issue i find this PR from xpad:
https://github.com/paroj/xpad/pull/224/files

i connect 8bitdo adapter to raspberry pi 4, update xpad as described at https://github.com/paroj/xpad#installing and xinput working! jstest, evtest and even fftest working correctly and with vibration. So, it seems lilke we need to update xpad on the tv?

**Comment by mariotaku** [comment]
@wiistriker Updating driver for the TV is not very practical. I think 8bitdo is doing something funny: When you connect it to the host, it expects a sequence of commands for the Xbox controller then it starts working. But on adapter V1 it doesn't require that sequence.

**Comment by wiistriker** [comment]
@mariotaku do you have v1 adapter? what is vid/pid of this device?

is there any way to change vid/pid of device in webos?

**Comment by kocane** [comment]
@mariotaku would you recommend getting the v1 adapter because of this issue? 

I use my 8bitdo Pro 2 with bluetooth on my LG C9 but for some reason I need to re-pair the controller each time I have turned the TV off. They connect to each other my the controller simply doesn't work. So I figure the wireless adapter is the way to go

**Comment by kocane** [comment]
What is recommended? To find a V1 adapter or use the V2 adapter with something else than xinput?

**Comment by mariotaku** [comment]
I would recommend Mayflash MAGIC-S Pro 2. It's tested to be working for newer Xbox controllers and works fine on webOS.

**Comment by mariotaku** [comment]
8bitdo controllers and adapters are not recommended since it can't work well on embedded Linux (like webOS). Closing this issue.

**Comment by kocane** [comment]
I went with a 8bitdo V1 adapter and it actually works alright.

**Comment by wiistriker** [comment]
@kocane vibrating too?
