### ISSUE TITLE
Stadia controller with Bluetooth LE not recognized

### ISSUE THREAD

**Issue by kentyman23** [mariotaku/moonlight-tv#210]
**Describe the bug**

I [updated](https://stadia.google.com/controller/) my old Stadia controller to use Bluetooth LE instead of Wi-Fi, but it doesn't work with Moonlight on my LG C2. For the record, it works great with the native GeForce Now app, so I know it can work on this TV.

**To Reproduce**

1. Ensure your Stadia controller is updated to work with Bluetooth LE: https://stadia.google.com/controller/
2. Pair it with your TV under Devices
3. Optional: Ensure it works well with GeForce Now app
4. Try to use with Moonlight but confirm that no button does anything
5. In Steam settings through Moonlight under Controllers, notice that it doesn't show any connected controllers

**Expected behavior**

It should work just as well as my other Bluetooth controllers

**Basic information**

 - Moonlight version: 1.5.3
 - Model: LC C2 [OLED55C2PUA](https://www.lg.com/us/tvs/lg-oled55c2pua)
 - webOS version: 7.3.0
 - Firmware: 03.30.16

**Additional context**

For the record, I got my Xbox controller working by [downgrading to not use Bluetooth LE](https://github.com/mariotaku/moonlight-tv/issues/190#issuecomment-1369310536). That said, this controller works fine with GeForce Now, so presumably can be made to work with Moonlight.

**Comment by mariotaku** [comment]
Hi, maybe the controller was not mapped yet. https://github.com/webosbrew/apps-repo/issues/77 I'll develop this app later for you to test the controller.

**Comment by davigamer987** [comment]
I'd also like this to work

**Comment by Stono** [comment]
Would love this too :D

**Comment by mariotaku** [comment]
I bought a Stadia controller and switched it to Bluetooth mode. And it turns out at least on my webOS 5 TV, input events can't get picked up at all. Not in moonlight, nor GeForce Now. Reading raw data from the OS won't produce anything either.

I tried a few gamepads and here is the result:

* Xbox One Controller: Working, mapping is correct
* Switch Pro Controller: Working except for snapshot button. Home = Guide button
* Stadia Controller: Can be paired, recognized by moonlight, but not producing any input event.
* Xbox Series Controller: Can't be paired at all

Although this can be varied between different TV models, I think Stadia Controller via Bluetooth can't work on some webOS TVs at all. One possible reason is it has newer BLE version for the TV to handle.

Please let me know if it has different situation on your TV, be sure to provide your TV model and webOS version.

**Comment by kentyman23** [comment]
It definitely works with my TV! Now, it is true that this controller is glitchy on many devices such that you have to [unpair/repair sometimes](https://www.reddit.com/r/LGOLED/comments/14920m6/stadia_controller_geforcenow/), but I use it with GeForce Now on my C2. From original post:

> Moonlight version: 1.5.3
> Model: LC C2 [OLED55C2PUA](https://www.lg.com/us/tvs/lg-oled55c2pua)
> webOS version: 7.3.0
> Firmware: 03.30.16

Can you try unpairing and re-pairing with GeForce Now? It definitely works for me.
