### ISSUE TITLE
Enabling Game Mode in moonlight App (LG C1)

### ISSUE THREAD

**Issue by felipe-ff** [mariotaku/moonlight-tv#220]
Hello, I'm trying to enable game mode in the app but I get a message saying it is only possible in an HDMI input.

Huge input lag without it... is it possible to enable it at all in moonlight app in LG C1 tv?

**Comment by IrbeinTepes** [comment]
happens in C2 as well, but I don't think you are able to manipulate it to work, TV can only access it if it's in hdmi port

**Comment by mariotaku** [comment]
You may want to check your picture mode. On the TVs I own, some will switch to "Game" automatically while some not. Non-game picture mode will have bigger input lag due to extra processing.

For example, on a webOS 4 TV, if you press ⚙️ button on your remote, you'll see a quick settings menu. Select picture mode.

![webos-dev-tmp-5253bec4-7f41-4e02-bc41-fd80df1a13b4](https://github.com/mariotaku/moonlight-tv/assets/830358/e0dbbaef-5124-41e3-bf30-06cf4218b95b)

and select "Game".

![webos-dev-tmp-45feca8a-291a-44bd-af5c-147922f894db](https://github.com/mariotaku/moonlight-tv/assets/830358/3de83544-0fa8-4e94-995d-a79558b2d0e1)

---

Also I did notice one some newer models, they have another "Game Optimizer", that's not for any kind of software based streaming.
