### ISSUE TITLE
[BUG] Crash on Start

### ISSUE THREAD

**Issue by krzyzakpl** [mariotaku/moonlight-tv#227]
## Basic information

 - Device model: (OLED77C2PUA) 
 - Firmware version: (03.33.16) 
 - webOS version: (7.3.0) 
 - Moonlight version: (1.5.7) 
 - Is audio working: (No) 
 - Is video working: (No) 
 - Is input working: (No) 

## Description

The Moonlight app will not launch. It fails to start. 

I made sure to follow the instractions correctly to enable Develope mode on my LG TV and i was able to run other Homebrew Apps. This helped me verify that the development process was applied correctly. 

I do see the Moonlight app on my LG TV's home screen (the gray wheel icon) 
Once i press the Moonlight app, the screen shows a full screen image of the Moonlight logo but after a second or two the app exits and goes back to the LG WEB OS main page. The moonlight app did not start.

Attached one of the crash reports i pulled from the web os dev manager.

I also tried previous verions with same resutls (version 1.5.2 and 1.4.9)

[CrashReport.txt](https://github.com/mariotaku/moonlight-tv/files/11730521/CrashReport.txt)

**Comment by mariotaku** [comment]
Hi, thanks a lot for the log! I'll take a look.

**Comment by szombi** [comment]
Hello!

I see same with my OLED65C21LA, firmware and webos versions are same as in the original post.

**Comment by mariotaku** [comment]
The log was very helpful. I have pinpointed the exact cause of this error, and a fix will be available soon.

**Comment by krzyzakpl** [comment]
Thanks for looking into this so quickly.
Also wanted to add that the next evening, i turend on my TV and tried to start the app again. Lo and behold it worked.
TV was off the whole day so not sure what changed. I was still on version 1.4.9. Updated to 1.5.7 and it is working as well.

Maybe the TV just needed a longer reboot? Hard to explain what changed. I have tried Turning it off and on when it was not working.

**Comment by mariotaku** [comment]
@krzyzakpl Hi, you are very lucky(?) that triggered this bug. Moonlight is supposed to load latest gamepad mapping while it doesn't, because it relies on an uninitialized variable to decide whether to start. Somehow last time when you use that it successfully triggered the code and caused it to crash.

There's nothing needed on your side for this issue, it was fixed in [v1.5.8](https://github.com/mariotaku/moonlight-tv/releases/tag/v1.5.8).

If you still have crashes, please send me error logs like you did. It helps pinpointing the issue very fast!
